[versions]
animation = "1.8.3"
appcompat = "1.7.1"
benchmarkMacroJunit4 = "1.4.0"
coilCompose = "2.7.0"
coilGif = "2.7.0"
compiler = "4.16.0"
compose-bom = "2025.07.00"
constraintlayout = "2.2.1"
constraintlayoutComposeAndroid = "1.1.1"
converterGson = "2.11.0"
datastorePreferences = "1.1.7"
espressoCore = "3.7.0"
firebaseCrashlyticsBuildtools = "3.0.5"
glide = "4.16.0"
gson = "2.13.1"
hiltCompiler = "1.2.0"
hiltNavigationFragment = "1.2.0"
hiltWork = "1.2.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinxCollectionsImmutable = "0.4.0"
lifecycle = "2.9.2"
hilt = "2.57"
loggingInterceptor = "5.1.0"
lottie = "6.6.7"
lottieCompose = "6.6.7"
material = "1.12.0"
media = "1.7.0"
media3Exoplayer = "1.8.0"
media3Ui = "1.8.0"
media3Session = "1.8.0"
navigation = "2.9.3"
core-ktx = "1.16.0"
activity-compose = "1.10.1"
playServicesLocation = "21.3.0"
profileinstaller = "1.4.1"
retrofit = "2.11.0"
review = "2.0.2"
reviewKtx = "2.0.2"
roomCompiler = "2.7.2"
roomRuntime = "2.7.2"
roomKtx = "2.7.2"
safeArgs = "2.9.3"
foundation = "1.9.2"
androidGradlePlugin = "8.13.1"
kotlin = "2.2.0"
baselineprofile = "1.4.0"
ksp = "2.2.0-2.0.2"
uiTestJunit4 = "1.8.3"
workRuntimeKtx = "2.10.3"

[libraries]
# Compose
android-lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
androidx-hilt-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

# Compose BOM
benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-kt-coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilGif" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }

# Lifecycle
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
constraintlayout-compose-android = { module = "androidx.constraintlayout:constraintlayout-compose-android", version.ref = "constraintlayoutComposeAndroid" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
firebase-crashlytics-buildtools = { module = "com.google.firebase:firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigationFragment" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# Core & Activity Compose
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

# Navigation
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Session" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-safe-args = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "safeArgs" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
review = { module = "com.google.android.play:review", version.ref = "review" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidTest = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "org.jetbrains.kotlin.kapt" }
navigation-safeArgs = { id = "androidx.navigation.safeargs.kotlin",  version.ref = "safeArgs" }